### ISSUE TITLE
Can I add customize text with loader?

### ISSUE THREAD

**Issue by hani455** [kdastan/react-native-modal-loader#8]

**Comment by kdastan** [comment]
Sure!

**Comment by hani455** [comment]
<Loader
          titleStyle={{color: 'red'}}
          title="Hahah"
          loading={isLoadingUnsaved}
          color="#1C3F3E"
        />
        I am using like this but title is not shown. Please tell me If I am doing anything wrong.

**Comment by kdastan** [comment]
Sorry, for long delay, I see that now package doesn't have titleStyle prop, need a sometime to add it, then you can use it as well.

**Comment by hani455** [comment]
No worries. But I have also use that prop but issue can't be resolved. Now I am using alternative package for performing the task named as **react-native-loading-spinner-overlay**.
